POST http://localhost:5000/api/auth/profile
Content-Type:application/json

{
   "email": "nkallamvalli11@gmail.com"

}

###
GET http://localhost:5000/api/auth/register
auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTVkZDRkM2RlZTczMGE1ZmZjYWU2NCIsImlhdCI6MTY1MDIzOTcxMiwiZXhwIjoxNjUwMjQwMzEyfQ.ZOt6q4eZ0benUYwRsoL9xdl9dErk7EIeFlXEKK15bek

###
GET http://localhost:5000/api/auth/profile
auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1ZGQ0ZDNkZWU3MzBhNWZmY2FlNjQiLCJpYXQiOjE2NTAyNDY4MTR9.E5V4xB0YnfRrVLwyO68WzxOfzBBLdN952To1w-OS-lg


###

POST http://localhost:5000/api/auth/tokenIsValid


###
POST http://localhost:5000/api/auth/forgotpassword
Content-Type:application/json

{
   "email": "nkallamvalli11@gmail.com"

}

###
PUT http://localhost:5000/api/auth/resetpassword/cfb57beef0f97a23a8cee994dc1087a61008bba6
Content-Type:application/json

{
   "password": "CEN3031"
}



